"rectype","issueid","project_owner","project_name","actor","time","text","action","title"
"issue_title","163","aio-libs","aioredis","pyup-bot","2016-11-12 15:29:43","
There's a new version of [pytest](https://pypi.python.org/pypi/pytest) available.
You are currently using **3.0.3**. I have updated it to **3.0.4**



These links might come in handy:  <a href=""http://pypi.python.org/pypi/pytest"">PyPI</a> | <a href=""https://pyup.io/changelogs/pytest/"">Changelog</a> | <a href=""http://pytest.org"">Homepage</a> 



### Changelog
> 
>### 3.0.4.dev0

>==========

>*

>* Import errors when collecting test modules now display the full traceback (`1976`_).
>  Thanks `cwitty`_ for the report and `nicoddemus`_ for the PR.

>* Fix confusing command-line help message for custom options with two or more ``metavar`` properties (`2004`_).
>  Thanks `okulynyak`_ and `davehunt`_ for the report and `nicoddemus`_ for the PR.

>* When loading plugins, import errors which contain non-ascii messages are now properly handled in Python 2 (`1998`_).
>  Thanks `nicoddemus`_ for the PR.

>* Fixed cyclic reference when ``pytest.raises`` is used in context-manager form (`1965`_). Also as a
>  result of this fix, ``sys.exc_info()`` is left empty in both context-manager and function call usages.
>  Previously, ``sys.exc_info`` would contain the exception caught by the context manager,
>  even when the expected exception occurred.
>  Thanks `MSeifert04`_ for the report and the PR.

>* Fixed false-positives warnings from assertion rewrite hook for modules that were rewritten but
>  were later marked explicitly by ``pytest.register_assert_rewrite``
>  or implicitly as a plugin (`2005`_).
>  Thanks `RonnyPfannschmidt`_ for the report and `nicoddemus`_ for the PR.

>* Report teardown output on test failure (`442`_).
>  Thanks `matclab`_ or the PR.

>* Fix teardown error message in generated xUnit XML.
>  Thanks `gdyuldin`_ or the PR.

>* Properly handle exceptions in ``multiprocessing`` tasks (`1984`_).
>  Thanks `adborden`_ for the report and `nicoddemus`_ for the PR.

>* Clean up unittest TestCase objects after tests are complete (`1649`_).
>  Thanks `d_b_w`_ for the report and PR.

>*

>*


>.. _adborden: https://github.com/adborden
>.. _cwitty: https://github.com/cwitty
>.. _d_b_w: https://github.com/d_b_w
>.. _gdyuldin: https://github.com/gdyuldin
>.. _matclab: https://github.com/matclab
>.. _MSeifert04: https://github.com/MSeifert04
>.. _okulynyak: https://github.com/okulynyak

>.. _442: https://github.com/pytest-dev/pytest/issues/442
>.. _1965: https://github.com/pytest-dev/pytest/issues/1965
>.. _1976: https://github.com/pytest-dev/pytest/issues/1976
>.. _1984: https://github.com/pytest-dev/pytest/issues/1984
>.. _1998: https://github.com/pytest-dev/pytest/issues/1998
>.. _2004: https://github.com/pytest-dev/pytest/issues/2004
>.. _2005: https://github.com/pytest-dev/pytest/issues/2005
>.. _1649: https://github.com/pytest-dev/pytest/issues/1649








*Got merge conflicts? Close this PR and delete the branch. I'll create a new PR for you.*

Happy merging! ðŸ¤–
","start issue","Update pytest to 3.0.4"
"issue_closed","163","aio-libs","aioredis","asvetlov","2016-11-12 23:11:13","","closed issue","Update pytest to 3.0.4"
"pull_request_title","163","aio-libs","aioredis","pyup-bot","2016-11-12 15:29:43","
There's a new version of [pytest](https://pypi.python.org/pypi/pytest) available.
You are currently using **3.0.3**. I have updated it to **3.0.4**



These links might come in handy:  <a href=""http://pypi.python.org/pypi/pytest"">PyPI</a> | <a href=""https://pyup.io/changelogs/pytest/"">Changelog</a> | <a href=""http://pytest.org"">Homepage</a> 



### Changelog
> 
>### 3.0.4.dev0

>==========

>*

>* Import errors when collecting test modules now display the full traceback (`1976`_).
>  Thanks `cwitty`_ for the report and `nicoddemus`_ for the PR.

>* Fix confusing command-line help message for custom options with two or more ``metavar`` properties (`2004`_).
>  Thanks `okulynyak`_ and `davehunt`_ for the report and `nicoddemus`_ for the PR.

>* When loading plugins, import errors which contain non-ascii messages are now properly handled in Python 2 (`1998`_).
>  Thanks `nicoddemus`_ for the PR.

>* Fixed cyclic reference when ``pytest.raises`` is used in context-manager form (`1965`_). Also as a
>  result of this fix, ``sys.exc_info()`` is left empty in both context-manager and function call usages.
>  Previously, ``sys.exc_info`` would contain the exception caught by the context manager,
>  even when the expected exception occurred.
>  Thanks `MSeifert04`_ for the report and the PR.

>* Fixed false-positives warnings from assertion rewrite hook for modules that were rewritten but
>  were later marked explicitly by ``pytest.register_assert_rewrite``
>  or implicitly as a plugin (`2005`_).
>  Thanks `RonnyPfannschmidt`_ for the report and `nicoddemus`_ for the PR.

>* Report teardown output on test failure (`442`_).
>  Thanks `matclab`_ or the PR.

>* Fix teardown error message in generated xUnit XML.
>  Thanks `gdyuldin`_ or the PR.

>* Properly handle exceptions in ``multiprocessing`` tasks (`1984`_).
>  Thanks `adborden`_ for the report and `nicoddemus`_ for the PR.

>* Clean up unittest TestCase objects after tests are complete (`1649`_).
>  Thanks `d_b_w`_ for the report and PR.

>*

>*


>.. _adborden: https://github.com/adborden
>.. _cwitty: https://github.com/cwitty
>.. _d_b_w: https://github.com/d_b_w
>.. _gdyuldin: https://github.com/gdyuldin
>.. _matclab: https://github.com/matclab
>.. _MSeifert04: https://github.com/MSeifert04
>.. _okulynyak: https://github.com/okulynyak

>.. _442: https://github.com/pytest-dev/pytest/issues/442
>.. _1965: https://github.com/pytest-dev/pytest/issues/1965
>.. _1976: https://github.com/pytest-dev/pytest/issues/1976
>.. _1984: https://github.com/pytest-dev/pytest/issues/1984
>.. _1998: https://github.com/pytest-dev/pytest/issues/1998
>.. _2004: https://github.com/pytest-dev/pytest/issues/2004
>.. _2005: https://github.com/pytest-dev/pytest/issues/2005
>.. _1649: https://github.com/pytest-dev/pytest/issues/1649








*Got merge conflicts? Close this PR and delete the branch. I'll create a new PR for you.*

Happy merging! ðŸ¤–
","e3bb0cef132f7b6dba523096d0c7db1ae1f61e87","Update pytest to 3.0.4"
"pull_request_merged","163","aio-libs","aioredis","asvetlov","2016-11-12 23:11:12","Update pytest to 3.0.4","f4645d6427e919f1efd3304b2f3b07381941907e","Pull request merge from aio-libs/aioredis:pyup-update-pytest-3.0.3-to-3.0.4 to aio-libs/aioredis:master"
"issue_comment","163","aio-libs","aioredis","codecov-io","2016-11-12 23:08:38","## [Current coverage](https://codecov.io/gh/aio-libs/aioredis/pull/163?src=pr) is 96.65% (diff: 100%)

> Merging [#163](https://codecov.io/gh/aio-libs/aioredis/pull/163?src=pr) into [master](https://codecov.io/gh/aio-libs/aioredis/branch/master?src=pr) will increase coverage by **0.01%**

``` diff
@@             master       #163   diff @@
==========================================
  Files            46         46          
  Lines          5555       5555          
  Methods           0          0          
  Messages          0          0          
  Branches        419        419          
==========================================
+ Hits           5368       5369     +1   
  Misses          142        142          
+ Partials         45         44     -1   
```

> Powered by [Codecov](https://codecov.io?src=pr). Last update [9cad997...e3bb0ce](https://codecov.io/gh/aio-libs/aioredis/compare/9cad997a5d70f8c3e4c73cf17f779d9792781569...e3bb0cef132f7b6dba523096d0c7db1ae1f61e87?src=pr)
","",""
"pull_request_commit","163","aio-libs","aioredis","pyup-bot","2016-11-12 15:29:42","Update pytest from 3.0.3 to 3.0.4","e3bb0cef132f7b6dba523096d0c7db1ae1f61e87",""
