"rectype","issueid","project_owner","project_name","actor","time","text","action","title"
"issue_title","132","idan","oauthlib","johanmeiring","2013-04-03 09:05:00","This PR fixes the following two inconsistencies:
- The docs for save_bearer_token() indicated that the ""scope"" key in the bearer token dict should be a list, when it is in fact a space-separated list of scopes wrapped in a string (not a list).  The documentation has been corrected.
- The docs for invalidate_authorization_code() indicated that the ""code"" key should be dict containing the authorization grant, when in fact the authorization grant (i.e. the string) itself is sent through to the function.  The documentation has been corrected.

This PR should close #130.
","start issue","Further documentation corrections"
"issue_closed","132","idan","oauthlib","ib-lundgren","2013-04-06 09:51:47","","closed issue","Further documentation corrections"
"pull_request_title","132","idan","oauthlib","johanmeiring","2013-04-03 09:05:00","This PR fixes the following two inconsistencies:
- The docs for save_bearer_token() indicated that the ""scope"" key in the bearer token dict should be a list, when it is in fact a space-separated list of scopes wrapped in a string (not a list).  The documentation has been corrected.
- The docs for invalidate_authorization_code() indicated that the ""code"" key should be dict containing the authorization grant, when in fact the authorization grant (i.e. the string) itself is sent through to the function.  The documentation has been corrected.

This PR should close #130.
","f90a3bdb79bef5a39322c4d04c1055683ddcc15d","Further documentation corrections"
"pull_request_merged","132","idan","oauthlib","ib-lundgren","2013-04-06 09:51:47","Further documentation corrections","550c92dcdbdec6e6278f2e0d5ea489f5bd8e19bb","Pull request merge from johanmeiring/oauthlib:master to idan/oauthlib:master"
"issue_comment","132","idan","oauthlib","ib-lundgren","2013-04-03 20:58:47","Excellent! Keep the PRs coming =) 

Just one small thing, please change headers.iteritems in django.py to headers.items (iteritems is not available in py3).
","",""
"issue_comment","132","idan","oauthlib","johanmeiring","2013-04-04 06:35:20","Done :)  Oddly enough it didn't work when I used items() yesterday, but something else was probably wrong (which was subsequently fixed)
","",""
"issue_comment","132","idan","oauthlib","ib-lundgren","2013-04-06 09:51:42","Thanks =) Probably solar flare...
","",""
"pull_request_commit","132","idan","oauthlib","johanmeiring","2013-04-03 08:57:08","Corrects two additional documentation inconsistencies","f2d2eadc6ff07fd9d8fc83d144ccc1e82b5480c2",""
"pull_request_commit","132","idan","oauthlib","johanmeiring","2013-04-03 12:47:17","Fixes decorators that were throwing errors","76e8bc7eff107000849f7428e469c70801680e3f",""
"pull_request_commit","132","idan","oauthlib","johanmeiring","2013-04-04 06:31:03","Changes iteritems to items for Py3 compatibility","f90a3bdb79bef5a39322c4d04c1055683ddcc15d",""
